/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Thu Mar 15 17:24:44 2018"
#define BUILD_TIME (1521159884L)

#define VERSION_NUMBER 0x00000707UL
#define VERSION_FEATURES 0x181fee4eUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x6126237dUL
#define VERSION_SANITY2 0xb08a0638UL

#define VERSION_STRING "0.0.7E7F2"
#define VERSION_ID \
 "Windows SlashEM tty Version 0.0.7E7F2 - last build Thu Mar 15 17:24:44 2018."
